CREATE TABLE IF NOT EXISTS public.roles(
	id SERIAL PRIMARY KEY,
	name CHARACTER VARYING(500),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP,
	CONSTRAINT name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.users(
	id SERIAL PRIMARY KEY,
	role_id BIGINT,
	name CHARACTER VARYING(500),
	email CHARACTER VARYING(500),
	password CHARACTER VARYING(500),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP,
	CONSTRAINT fk_role FOREIGN KEY(role_id) REFERENCES roles(id)
);

CREATE TABLE IF NOT EXISTS public.cities(
	id SERIAL PRIMARY KEY,
	name CHARACTER VARYING(500),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.buses(
	id SERIAL PRIMARY KEY,
	plate CHARACTER VARYING(10) NOT NULL,
	model CHARACTER VARYING(500) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.seats(
	id SERIAL PRIMARY KEY,
	bus_id BIGINT,
	name CHARACTER VARYING(500),
	description CHARACTER VARYING(500),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP,
	CONSTRAINT fk_bus FOREIGN KEY(bus_id) REFERENCES buses(id)
);

CREATE TABLE IF NOT EXISTS public.trips(
	id SERIAL PRIMARY KEY,
	origin_id BIGINT,
	destination_id BIGINT, 
	bus_id BIGINT,
	seat_id BIGINT,
	tripdate TIMESTAMP NOT NULL,
	price FLOAT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP,
	CONSTRAINT fk_origin FOREIGN KEY(origin_id) REFERENCES cities(id),
	CONSTRAINT fk_destination FOREIGN KEY(destination_id) REFERENCES cities(id),
	CONSTRAINT fk_seat FOREIGN KEY(seat_id) REFERENCES seats(id)
);

CREATE TABLE IF NOT EXISTS public.reservations(
	id SERIAL PRIMARY KEY,
	user_id BIGINT,
	trip_id BIGINT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP,
	CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id),
	CONSTRAINT fk_trip FOREIGN KEY(trip_id) REFERENCES trips(id)
);
